import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import ConnectWallet from "@/components/ConnectWallet";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="border-b">
          <div className="flex h-16 items-center px-4 max-w-7xl mx-auto">
            <div className="mr-8 flex items-center">
              <Link href="/" className="flex items-center">
                <span className="text-xl font-bold">Logo</span>
              </Link>
            </div>
            <div className="flex items-center gap-6">
              <Link href="/" className="text-sm font-medium transition-colors hover:text-primary">
                Home
              </Link>
            </div>
            <div className="ml-auto">
              <ConnectWallet />
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
