// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
  TYPESENSE_API_KEY: string;
  GROQ_API_KEY: string;
  APIFY_API_KEY: string;
  PINECONE_API_KEY: string;
  XHANDLES: DurableObjectNamespace<XHandlesObject>;
  TWEETS_BUCKET: R2Bucket;
  ERROR_BUCKET: R2Bucket;
  ERROR_QUEUE: Queue;
  TWEETS_SCRAPER_QUEUE: Queue;
  AI_ANALYZER_QUEUE: Queue;
  SAVE_TWEETS_QUEUE: Queue;
  AI: Ai;
}
