// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	TYPESENSE_API_KEY: string;
	GROQ_API_KEY: string;
	APIFY_API_KEY: string;
	XHANDLES: DurableObjectNamespace<XHandlesObject>;
	TWEETS_BUCKET: R2Bucket;
	ERROR_BUCKET: R2Bucket;
	ERROR_QUEUE: Queue;
	AI: Ai;
}
