// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
  TYPESENSE_API_KEY: string;
  GROQ_API_KEY: string;
  APIFY_API_KEY: string;
  FAUNA_SECRET: string;
  USERS: DurableObjectNamespace<UsersObject>;
  AI: Ai;
}
